include: package:lints/recommended.yaml

analyzer:
  exclude: [lib/**.g.dart, lib/generated_plugin_registrant.dart]

linter:
  rules:
    - require_trailing_commas
    - prefer_relative_imports
    - avoid_void_async
