name: stream_browser
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  socket_io_client: ^3.1.1
  json_annotation: ^4.9.0
  intl: ^0.18.1
  gif: ^2.3.0
  go_router: ^14.2.8
  js: ^0.6.7
  resizable_widget: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/MinecraftRegular-Bmg3.otf

    - family: Minecraft-Ten
      fonts:
        - asset: assets/fonts/MinecraftTen-VGORe.ttf

    - family: Pokemon-Pixel
      fonts:
        - asset: assets/fonts/pokemon_pixel_font.ttf
